### ISSUE TITLE
Postsにたどり着くことができない。

### ISSUE THREAD

**Issue by mizphses** [coderdojo-konan/website#9]
# Overview
ページをデプロイして確かめた感じ、postsページや各投稿は反映されているものの、そこへたどり着く手段が直接リンクを貼るしかない状況ではないのではないか。
この場合、公開したお知らせを見られる人が~~/posts/の存在を知る人のみとなってしまいます。
つきましては、Postsの閲覧手段をなんかしらの形で実装すべきです。

# Suggestion
* ナビゲーション部分にPOSTSのリンクを作る
* フロントページに「最新の投稿」など、閲覧するための部分を設ける

**Comment by yum45f** [comment]
@7io63

いいと思います！
PR開いてくれたら見ますよ〜 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mizphses** [comment]
#12でとりあえずの修正版を投稿しています。Review願います。
